# Generated by Django 4.0.2 on 2022-03-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colors', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('grey', 'Silver')], default='black', max_length=20)),
                ('available', models.IntegerField(default=0)),
                ('inStock', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('limited', 'Limited (< 10 )')], default='No', max_length=20)),
                ('added_on', models.DateField(auto_now=True)),
                ('barcode', models.IntegerField(default=1234567890)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products_cart.category')),
            ],
            options={
                'ordering': ('-title', 'price', '-added_on'),
            },
        ),
    ]
