# Generated by Django 4.0.2 on 2022-03-06 14:30

from django.db import migrations, models
import products_cart.models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='empty_cart.png', upload_to=products_cart.models.upload_to, verbose_name='Image'),
        ),
    ]
