# Generated by Django 4.0.2 on 2022-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
