# Generated by Django 4.0.2 on 2022-03-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0004_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
