# Generated by Django 4.0.2 on 2022-03-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0005_remove_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
