# Generated by Django 4.0.2 on 2022-03-06 18:34

from django.db import migrations, models
import products_cart.models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0007_category_image_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='empty_cart.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fname',
            field=models.CharField(default='fname_', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='empty_cart.png', upload_to=products_cart.models.upload_to, verbose_name='Product_image'),
        ),
    ]
