# Generated by Django 4.0.2 on 2022-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0008_customer_avatar_customer_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='Lname_', max_length=100),
        ),
    ]
