# Generated by Django 4.0.2 on 2022-03-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0009_remove_customer_avatar_customer_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
