# Generated by Django 4.0.2 on 2022-03-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0010_remove_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inStock',
        ),
    ]
