# Generated by Django 4.0.2 on 2022-03-06 20:34

from django.db import migrations, models
import products_cart.models


class Migration(migrations.Migration):

    dependencies = [
        ('products_cart', '0011_remove_product_available_remove_product_cat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('grey', 'Silver')], default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='inStock',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('limited', 'Limited (< 10 )')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='empty_cart.png', upload_to=products_cart.models.upload_to, verbose_name='Product_image'),
        ),
    ]
